# Release branches where trunk branches are merge-committed to trigger releases

#release:
#- base-branch:
#  - 'main'
#  - 'maintenance/.+/[0-9]+\.([0-9]+|x)\.x'

# Label any maintenance branch, trunk and release

maintenance:
- base-branch:
  - 'maintenance/.+/[0-9]+\.([0-9]+|x)\.x'

# Label PRs into the main branch

#main:
#- base-branch:
#  - 'main'

# Labels for PRs on asset specific branches

controller-container:
- base-branch:
  - '.+/controller-container(/.+)?'

trino-container:
- base-branch:
  - '.+/trino-container(/.+)?'

fizzbuzz-chart:
- base-branch:
  - '.+/fizzbuzz-chart(/.+)?'

fizzbuzz-crds-chart:
- base-branch:
  - '.+/fizzbuzz-crds-chart(/.+)?'
