release:
- base-branch:
  - 'release/.+'
  - 'maintenance/.+/[0-9]+\.([0-9]+|x)\.x'

trunk:
- base-branch:
  - 'main'
  - 'maintenance/.+/trunk/[0-9]+\.([0-9]+|x)\.x'

maintenance:
- base-branch:
  - 'maintenance/.+/.+'

controller-container:
- base-branch:
  - '.+/controller-container(/.+)?'

fizzbuzz-chart:
- base-branch:
  - '.+/fizzbuzz-chart(/.+)?'

fizzbuzz-crds-chart:
- base-branch:
  - '.+/fizzbuzz-crds-chart(/.+)?'
