release:
  - base-branch:
      - 'release/*'
      - 'maintenance/*/[0-9]+.x.x'
      - 'maintenance/*/[0-9]+.[0-9]+.x'

trunk:
  - base-branch:
      - 'main'
      - 'maintenance/*/trunk/[0-9]+.x.x'
      - 'maintenance/*/trunk/[0-9]+.[0-9]+.x'

maintenance:
  - base-branch:
      - 'maintenance/**'

controller-container:
  - base-branch:
      - '*/controller-container'
      - '*/controller-container/*'
