apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: fizzbuzzs.fizzbuzz.ukserp.ac.uk
spec:
  group: fizzbuzz.ukserp.ac.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                n:
                  type: integer
                  description: Fizzbuzz input N.
  scope: Namespaced
  names:
    plural: fizzbuzzs
    singular: fizzbuzz
    kind: Fizzbuzz
