name: Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: lint pr title
        shell: bash
        run: |
          echo "$TITLE" | npx commitlint --config .github/commitlint.config.js
        env:
          TITLE: ${{ github.event.pull_request.title }}
