name: Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint-pr-title:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - name: clone config from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/commitlint.config.js

      - name: cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ github.workflow }}-commitlint

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install commitlint
        shell: bash
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: lint pr title
        id: commitlint
        shell: bash
        run: |
          output=$(echo "$TITLE" | npx commitlint --config="$CONFIG")
          echo "output=$output" >> "$GITHUB_OUTPUT"
        env:
          TITLE: ${{ github.event.pull_request.title }}
          CONFIG: .github/commitlint.config.js

      - name: annotate commitlint output
        if: always()
        shell: bash
        run: >-
          echo "::error title=${{ steps.commitlint.outputs.output }}"
