name: Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint-pr-title:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - name: clone config from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/commitlint.config.mjs

      - name: cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ github.workflow }}-commitlint

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install commitlint
        shell: bash
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: lint pr title
        id: commitlint
        shell: bash
        run: |
          echo "$TITLE" | npx commitlint --config="$CONFIG"
        env:
          TITLE: ${{ github.event.pull_request.title }}
          CONFIG: .github/commitlint.config.mjs

      - name: Create error label
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "FIX PR TITLE",
              color: "#D93F0B"
            });

      - name: Remove error label on successful lint
        uses: actions/github-script@v6
        if: success()
        with:
          script: |
            github.rest.issues.removeLabels({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "FIX PR TITLE"
            })

      - name: Add error label on bad lint
        uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["FIX PR TITLE"]
            })