name: Fizzbuzz CRDs Chart

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/fizzbuzz-crds-chart.yaml'
      - 'charts/fizzbuzz-crds/**'
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'main'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/fizzbuzz-crds-chart.yaml'
      - 'charts/fizzbuzz-crds/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  fizzbuzz-crds-chart:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-chart.yaml@feat/kubeconform
    with:
      job-name: fizzbuzz-crds-chart
      comment-pr: "true"
      comment-release: "true"
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-project: ${{ vars.HARBOR_PROJECT }}
      registry-repo: fizzbuzz-crds
      release-tag-format: 'v${version}-fizzbuzz-crds-chart'
      notation-cert: ${{ vars.NOTATION_CERT }}
      chart: charts/fizzbuzz-crds
      test-command: |
        helm template $CHART --debug

    secrets:
      notation-key: ${{ secrets.NOTATION_KEY }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
