name: Fizzbuzz Chart

on:
  pull_request:
    branches-ignore:
      - '*/controller-container*'
      - '*/fizzbuzz-crds-chart*'
    paths:
      - '.github/workflows/fizzbuzz-chart.yaml'
      - 'charts/fizzbuzz/**'
  push:
    branches:
      - 'maintenance/fizzbuzz-chart/[0-9]+.x.x'
      - 'maintenance/fizzbuzz-chart/[0-9]+.[0-9]+.x'
      - 'release/fizzbuzz-chart'
    paths:
      - '.github/workflows/fizzbuzz-chart.yaml'
      - 'charts/fizzbuzz/**'

permissions:
  contents: write
  pull-requests: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  fizzbuzz-chart:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-chart.yaml@v1.2.0-charts
    with:
      job-name: fizzbuzz-chart
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-project: ${{ vars.HARBOR_PROJECT }}
      registry-repo: fizzbuzz
      release-tag-format: 'fizzbuzz-chart-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/fizzbuzz
      test-command: |
        helm template $CHART --debug

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
