name: PR Label

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
      - 'release/*'
      - 'maintenance/*/[0-9]+.x.x'
      - 'maintenance/*/[0-9]+.[0-9]+.x'

jobs:
  pr-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: release
