name: Renovate Bot

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - uses: SwanseaUniversityMedical/workflows/.github/actions/renovate@feat/renovate
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ secrets.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
