name: Renovate Bot

on:
  pull_request:
    paths:
      - '.github/workflows/renovate.yaml'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1-5'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - uses: SwanseaUniversityMedical/workflows/.github/actions/renovate@v1.0.9-renovate-action
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
