name: vcluster-test
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux, vcluster]
    steps:
      - run: hostname && uname -a
      - run: docker version
      - run: docker run --rm hello-world