name: Whalesay-Container

on:
  merge_group:
  pull_request:
    paths:
      - '.github/workflows/Whalesay-Container.yaml'
      - 'containers/whalesay/**'
#  push:
#    branches:
#      - main
#    paths:
#      - '.github/workflows/Whalesay-Container.yaml'
#      - 'containers/whalesay/**'


permissions:
  contents: write
  pull-requests: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  container-whalesay:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v1.4.2-containers
    with:
      job-name: container-whalesay
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/workflows-test
      release-tag-format: 'whalesay-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: containers/whalesay/Dockerfile
      build-context: containers/whalesay
      test-args: cowsay boo
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
#  whalesay:
#    runs-on:
#      labels: [ self-hosted, linux, x64 ]
#      group: heavy
#    steps:
#      - name: login to container registry
#        run: |
#          echo 'Hello World'
#      - name: Run slow CI (emulated by a long sleep)
#        run: sleep 60




