name: Lint Workflows-Test Yaml

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/yamllint.yaml@v1.1.2-yaml-linting
    with:
      config-file: .github/.yamllint.yaml

